# oh-my-zsh
- name: Install oh-my-zsh
  shell: set -o pipefail && curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  args:
    creates: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/"
  tags: zsh
