- name: Set Desktop to the bottom right hot corner
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-br-corner
    type: int
    value: 4
  tags: [dock, osx_defaults]
  notify:
    - Refresh Dock

- name: Tell modifier of bottom right hot corner to be changed
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-br-modifier
    type: int
    value: 0
  tags: [dock, osx_defaults]
  notify:
    - Refresh Dock

- name: Set Mission Control to the bottom left hot corner
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-bl-corner
    type: int
    value: 2
  tags: [dock, osx_defaults]
  notify:
    - Refresh Dock

- name: Tell modifier of bottom left hot corner to be changed
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-bl-modifier
    type: int
    value: 0
  tags: [dock, osx_defaults]
  notify:
    - Refresh Dock

- name: Set Sleep to the top left hot corner
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-tl-corner
    type: int
    value: 10
  tags: [dock, osx_defaults]
  notify:
    - Refresh Dock

- name: Tell modifier of top left hot corner to be changed
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-tl-modifier
    type: int
    value: 0
  tags: [dock, osx_defaults]
  notify:
    - Refresh Dock

- name: Set Launchpad to the top right hot corner
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-tr-corner
    type: int
    value: 11
  tags: [dock, osx_defaults]
  notify:
    - Refresh Dock

- name: Tell modifier of top right hot corner to be changed
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-tr-modifier
    type: int
    value: 0
  tags: [dock, osx_defaults]
  notify:
    - Refresh Dock

- name: Hide automatically the doc
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: int
    value: 1
  tags: [dock, osx_defaults]
  notify:
    - Refresh Dock

- name: Set key repeat interval
  community.general.osx_defaults:
    key: KeyRepeat
    type: int
    value: 1
  tags: [keyrepeat, osx_defaults]

- name: Set time to start key repeats
  community.general.osx_defaults:
    key: InitialKeyRepeat
    type: int
    value: 15
  tags: [keyrepeat, osx_defaults]

- name: Configure mouse speed
  community.general.osx_defaults:
    domain: com.apple.mouse
    key: scaling
    value: 3
  tags: [mouse, osx_defaults]

- name: Show hidden files on Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
  tags: [finder, osx_defaults]
  notify:
    - Refresh Finder

- name: Avoid creating .DS_Store files on network volumes
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
  tags: [osx_defaults]

- name: Avoid creating .DS_Store files on USB volumes
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true
  tags: [osx_defaults]
