---
- git_config: name=user.name scope=global value="{{ gitname }}"
  tags: gitconfig

- git_config: name=user.email scope=global value="{{ gitmail }}"
  tags: gitconfig

- git_config: name=color.ui scope=global value=true
  tags: gitconfig

- git_config: name=core.editor scope=global value="{{ editor }}"
  tags: gitconfig

- git_config: name=core.excludesfile scope=global value="{{ excludes_path }}"
  tags: gitconfig
