- name: Configure user.name of .gitconfig globally
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ gitname }}"
  tags: gitconfig

- name: Configure user.email of .gitconfig globally
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ gitmail }}"
  tags: gitconfig

- name: Configure color.ui of .gitconfig globally
  community.general.git_config:
    name: color.ui
    scope: global
    value: true
  tags: gitconfig

- name: Configure core.editor of .gitconfig globally
  community.general.git_config:
    name: core.editor
    scope: global
    value: "{{ editor }}"
  tags: gitconfig

- name: Configure core.excludefile of .gitconfig globally
  community.general.git_config:
    name: core.excludesfile
    scope: global
    value: "{{ excludes_path }}"
  tags: gitconfig
